In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#Here i am reading the files from my document directory
filepath=r'C:\Users\user\Documents\correlation.csv';
file=pd.read_csv (filepath);

In [ ]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       9 non-null      int64
 1   5       9 non-null      int64
dtypes: int64(2)
memory usage: 208.0 bytes

In [ ]:
#I am applying the pearson correlation concept 
corr_matrix = file.corr().abs()

print(corr_matrix)
# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# Find index of feature columns with correlation greater than 0.95
to_drop = [column for column in upper.columns if any(upper[column] > 0.85)]
#Here we print the correlation matrix which is in upper-trianguar form

          1         5
1  1.000000  0.595604
5  0.595604  1.000000

In [ ]:
#here we can see in the below output that since the correlation between the elements next to each other is less that 0.85 
#none of the elements are dropped

file.drop(file[to_drop], axis=1)

    1  5
0   2  6
1   3  7
2   4  8
3   5  9
4   6  4
5   7  3
6   8  2
7   9  1
8  10  6